core/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from home import views as home

urlpatterns = [
    # plugin apps
    url(r'^x/', include(admin.site.urls)),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
]

urlpatterns += [
    # user pages (home app)
    url(r'^$', home.index, name='index'),
    url(r'^pages/(?P<slug>\w+)/$', home.customized_page, name='customized_page'),
    url(r'^contact/$', home.contact, name='contact'),
    url(r'^apply/$', home.apply, name='apply'),
]

dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',
        views.index, name='index'),
    url(r'^login/$',
        views.login_user, name='login_user'),
    url(r'^snippets/$',
        views.snippets, name='snippets'),
    url(r'^pages/$',
        views.pages, name='pages'),
    url(r'^images/$',
        views.images, name='images'),
    url(r'^applicants/$',
        views.applicants, name='applicants'),
    url(r'^snippets/new/$',
        views.new_snippet, name='new_snippet'),
    url(r'^snippets/(?P<snippet_id>\d+)/$',
        views.update_snippet, name='update_snippet'),
    url(r'^pages/new/$',
        views.new_page, name='new_page'),
    url(r'^pages/(?P<page_id>\d+)/$',
        views.update_page, name='update_page'),
    url(r'^pages/preview/(?P<page_id>\d+)/$',
        views.preview_page, name='preview_page'),
    url(r'^images/new/$',
        views.new_images, name='new_images'),
]

dashboard/models.py
from django.db import models


class Snippet(models.Model):
    subject = models.CharField(max_length=140)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return '{} ({})'.format(self.subject, self.updated)

    def has_pos(self):
        return len(SnippetPos.objects.filter(snippet=self)) == 1


class Img(models.Model):
    url = models.URLField()
    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True, editable=False)


class Page(models.Model):
    subject = models.CharField(max_length=140)
    content = models.TextField(blank=True)
    style = models.TextField(blank=True)
    javascript = models.TextField(blank=True)
    is_inherited = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return '{} ({})'.format(self.subject, self.updated)

    def has_pos(self):
        return len(PagePos.objects.filter(page=self)) == 1


class Position(models.Model):
    slug = models.SlugField(unique=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.slug


class SnippetPosManager(models.Manager):

    def get_snippet(self, **kwargs):
        sp = self.filter(**kwargs)
        return sp[0].snippet if sp else None


class SnippetPos(Position):
    snippet = models.OneToOneField(Snippet, related_name="position", null=True, blank=True)
    objects = SnippetPosManager()

    class Meta:
        verbose_name_plural = "Snippet Positons"


class PagePosManager(models.Manager):

    def get_page(self, **kwargs):
        pp = self.filter(**kwargs)
        return pp[0].page if pp else None

    def get_headers(self):
        raw_setting = SiteSetting.get('header_links')
        links = raw_setting.split('|')
        return self.filter(slug__in=links)


class PagePos(Position):
    page = models.OneToOneField(Page, related_name="position", null=True, blank=True)
    objects = PagePosManager()

    class Meta:
        verbose_name_plural = "Page Positons"

    @property
    def route(self):
        return u'/pages/{slug}'.format(slug=self.slug)


class ImgPos(Position):
    img = models.ForeignKey(Img, related_name="position", null=True, blank=True)

    class Meta:
        verbose_name_plural = "Img Positons"


class SiteSetting(models.Model):
    key = models.SlugField(unique=True)
    value = models.CharField(max_length='50', blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return '{ "%s": "%s" }' % (self.key, self.value)

    # needn't a set method cus it's for administrator in admin
    @classmethod
    def get(cls, k, default=None):
        k_set = cls.objects.filter(key=k)
        return default if len(k_set) < 1 else k_set[0].value

dashboard/forms.py
from django import forms
from .models import Snippet, Page, Img, SnippetPos, PagePos


class StyledModelForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(StyledModelForm, self).__init__(*args, **kwargs)
        for field in self.fields.itervalues():
            field.widget.attrs['class'] = 'form-control'


class SnippetForm(StyledModelForm):

    POSITION_CHOICES = (('', '----------'),) + \
        tuple((sp.slug, sp.slug) for sp in SnippetPos.objects.all())

    position = forms.CharField(
        required=False,
        label='position',
        widget=forms.Select(
            choices=POSITION_CHOICES,
        ),
    )

    class Meta:
        model = Snippet
        fields = ['subject', 'content', 'position']

    def __init__(self, *args, **kwargs):
        super(SnippetForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs['rows'] = 25

    def save(self):
        instance = super(SnippetForm, self).save()

        original_snippet_pos_set = SnippetPos.objects.filter(snippet=instance)
        if len(original_snippet_pos_set) == 1:
            original_snippet_pos_set[0].snippet = None
            original_snippet_pos_set[0].save()

        position = self.clean().get('position', '')
        snippet_pos_set = SnippetPos.objects.filter(slug=position)
        if len(snippet_pos_set) == 1:
            snippet_pos_set[0].snippet = instance
            snippet_pos_set[0].save()

        return instance


class PageForm(StyledModelForm):

    POSITION_CHOICES = (('', '----------'),) + \
        tuple((pp.slug, pp.route) for pp in PagePos.objects.all())

    position = forms.CharField(
        required=False,
        label='position',
        widget=forms.Select(
            choices=POSITION_CHOICES,
        ),
    )

    class Meta:
        model = Page
        fields = ['subject', 'style', 'content', 'javascript', 'position', 'is_inherited']

    def __init__(self, *args, **kwargs):
        super(PageForm, self).__init__(*args, **kwargs)
        self.fields['style'].widget.attrs['rows'] = 3
        self.fields['javascript'].widget.attrs['rows'] = 3
        self.fields['content'].widget.attrs['rows'] = 25
        self.fields['position'].label = u'Route'
        self.fields['is_inherited'].label = u'Inherit original framework'

    def save(self):
        instance = super(PageForm, self).save()

        original_page_pos_set = PagePos.objects.filter(page=instance)
        if len(original_page_pos_set) == 1:
            original_page_pos_set[0].page = None
            original_page_pos_set[0].save()

        position = self.clean().get('position', '')
        page_pos_set = PagePos.objects.filter(slug=position)
        if len(page_pos_set) == 1:
            page_pos_set[0].page = instance
            page_pos_set[0].save()

        return instance


class ImgForm(forms.ModelForm):

    class Meta:
        model = Img
        fields = ['url']

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, Http404
from home.models import Message, Applicant
from .models import Snippet, Page, Img
from .forms import SnippetForm, PageForm, ImgForm

dashboard_login_required = login_required(login_url='/dashboard/login/')


@dashboard_login_required
def index(request):
    messages = Message.objects.order_by('-updated')
    return render(request, 'dashboard/index.html', locals())


@dashboard_login_required
def snippets(request):
    snippets = Snippet.objects.order_by('-updated')
    return render(request, 'dashboard/snippets.html', locals())


@dashboard_login_required
def pages(request):
    pages = Page.objects.order_by('-updated')
    return render(request, 'dashboard/pages.html', locals())


@dashboard_login_required
def images(request):
    images = Img.objects.order_by('-updated')
    return render(request, 'dashboard/images.html', locals())


@dashboard_login_required
def applicants(request):
    applicants = Applicant.objects.order_by('-updated')
    return render(request, 'dashboard/applicants.html', locals())


@dashboard_login_required
def new_snippet(request):
    form = SnippetForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect(reverse('dashboard:snippets'))

    return render(request, 'dashboard/edit_snippet.html', locals())


@dashboard_login_required
def update_snippet(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    initial = {}
    if snippet.has_pos():
        initial = {'position': snippet.position.slug}

    form = SnippetForm(request.POST or None, initial=initial, instance=snippet)

    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect(reverse('dashboard:snippets'))

    return render(request, 'dashboard/edit_snippet.html', locals())


@dashboard_login_required
def new_page(request):
    form = PageForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect(reverse('dashboard:pages'))

    return render(request, 'dashboard/edit_page.html', locals())


@dashboard_login_required
def update_page(request, page_id):
    page = get_object_or_404(Page, pk=page_id)
    initial = {}
    if page.has_pos():
        initial = {'position': page.position.slug}

    form = PageForm(request.POST or None, initial=initial, instance=page)

    if request.method == "POST" and form.is_valid():
        form.save()
        return redirect(reverse('dashboard:pages'))

    return render(request, 'dashboard/edit_page.html', locals())


@dashboard_login_required
def preview_page(request, page_id):
    page = get_object_or_404(Page, pk=page_id)
    print page.subject
    return render(request, 'home/customized_page.html', locals())


@dashboard_login_required
@csrf_exempt
def new_images(request):

    if request.method == "POST":

        failed = []
        for url in request.POST['urls'].split():
            form = ImgForm({'url': url})
            if form.is_valid():
                form.save()
            else:
                failed.append(url)

        return HttpResponse(u'\n'.join(failed) or 'success')

    else:
        raise Http404


def login_user(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next', reverse('dashboard:index'))
            return redirect(next_url)
        else:
            message = "The username and password were incorrect."

    return render(request, 'dashboard/login.html', locals())

dashboard/templates/dashboard/applicants.html
{% extends "dashboard/base.html" %}

{% block main %}
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="ghj">Applicants</h3>
                <table class="table table-bordered">
                    <thead>
                        <td>Name</td>
                        <td>Mail</td>
                        <td>Experiences</td>
                    </thead>
                    <tbody>
                        {% for a in applicants %}
                        <tr>
                            <td>{{ a.first_name }} {{ a.last_name }}</td>
                            <td>{{ a.email }}</td>
                            <td>{{ a.experiences|truncatechars:50 }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>GLE Dashboard</title>

    {% block style %}
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <link href="/static/css/dashboard.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="{% url 'dashboard:index' %}">
                        GLE Dashboard
                    </a>
                </li>
                <li>
                    <a href="{% url 'dashboard:index' %}">Messages</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:snippets' %}">Snippets</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:pages' %}">Pages</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:images' %}">Images</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:applicants' %}">Applicants</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        {% block main %}
        {% endblock %}

    </div>

    {% block foot_js %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>
    {% endblock %}

</body>

</html>

dashboard/templates/dashboard/edit_page.html
{% extends "dashboard/base.html" %}

{% block main %}
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <form method="POST">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class={% if forloop.last %}"form-inline"{%else%}"form-group"{%endif%}>
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                        {% if forloop.last %}
                        &nbsp;&nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-primary">Submit</button>
                        {% endif %}
                    </div>
                    {% endfor %}

                    {{ form.non_field_errors }}

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/edit_snippet.html
{% extends "dashboard/base.html" %}

{% block main %}
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <form method="POST">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class={% if forloop.last %}"form-inline"{%else%}"form-group"{%endif%}>
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                        {% if forloop.last %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                        {% endif %}
                    </div>
                    {% endfor %}

                    {{ form.non_field_errors }}

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/images.html
{% extends "dashboard/base.html" %}

{% block style %}
{{ block.super }}
<style>
    .thumbnail {
        height: 350px;
        overflow: auto;
    }
    .thumbnail img {
        height: 220px;
    }
    .caption, .modal-body, .modal-footer {
        text-align: center;
    }
    .modal-body img {
        max-width: 570px;
    }
</style>
{% endblock %}

{% block main %}
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">

            <div class="col-lg-12">
                <h3 class="ghj">Images</h3>
            </div>

            <div class="col-lg-3">
                <div class="thumbnail">
                    <img id="img-upload" src="/static/images/upload.png">
                    <div class="caption">
                        <hr>
                        <input id="input-upload" type="filepicker" data-fp-apikey="ANXk2hzB0TUfODjaxKHWKz" data-fp-mimetypes="image/*" data-fp-container="modal" data-fp-multiple="true" onchange="save_img_urls(event.fpfiles)">
                    </div>
                </div>
            </div>

            {% for s in images %}
            <div class="col-lg-3">
                <div class="thumbnail">
                    <img class="uploaded-img" src="{{ s.url }}">
                    <hr>
                    <div class="caption">
                        <h3>Position</h3>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>

    <!-- popup -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Image</h4>
                </div>
                <div class="modal-body">
                    <img><p><br><code></code></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block foot_js %}
{{ block.super }}
<script type="text/javascript" src="//api.filepicker.io/v2/filepicker.js"></script>
<script>
    function parse_img_urls(imgs) {
        var out='';
        for(var i=0; i < imgs.length; i++) {
            out += imgs[i].url;
            out += '\n';
        };
        return out;
    }

    function save_img_urls(imgs) {
        var failed_msg = "Upload failed! Please refresh page and try again."
        var request = $.ajax({
            method: 'POST',
            url: "{% url 'dashboard:new_images' %}",
            data: {"urls": parse_img_urls(imgs)}
        })
        request.done(function(msg) {
            if (msg === 'success') {
                window.location.reload();
            }
            else {
                alert('Failed on:\n\n' + msg + '\n\nPlease send this message to admin!');
            }
        });
        request.fail(function(jqXHR, textStatus) {
            alert(failed_msg);
        });
    };

    /* active popup */
    $('.thumbnail .uploaded-img').click(function(ev) {
        ev.preventDefault();
        $('#myModal').modal();
        $('#myModal .modal-body img').attr("src", ev.currentTarget.currentSrc);
        $('#myModal .modal-body code').html(ev.currentTarget.currentSrc);
    });

    /* active upload */
    $('#img-upload').click(function(ev) {
        ev.preventDefault();
        $('.fp__btn').click();
    });
</script>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends "dashboard/base.html" %}

{% block main %}
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div class="distracted">
                    <h3 class="ghj">Messages</h3>
                    {% for m in messages %}
                    <div class="well">
                        <h4>{{ m.subject }}</h4>
                        <p>
                            <em>{{ m.visitor.name }}({{ m.visitor.email }})</em> said:<br>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ m.content }}
                        </p>
                        <br>
                        <footer>At {{ m.created }}</footer>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/login.html
{% extends "dashboard/base.html" %}

{% block main %}
<br>
<br>
<br>
<form class="form-horizontal" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="username" class="col-sm-2 control-label">Username</label>
        <div class="col-sm-4">
            <input name="username" class="form-control" id="username" placeholder="Username">
        </div>
    </div>
    <div class="form-group">
        <label for="password" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-4">
            <input name="password" type="password" class="form-control" id="password" placeholder="Password">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            <span style="color:red">{{ message }}</span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
    </div>
</form>
{% endblock %}

dashboard/templates/dashboard/pages.html
{% extends "dashboard/base.html" %}

{% block main %}
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="ghj">Pages</h3>
                <h2><a class="label label-primary" href="{% url 'dashboard:new_page' %}">New</a></h2>
                <br>
                <table class="table table-bordered">
                    <thead>
                        <td>Pub_date</td>
                        <td>Route</td>
                        <td>Subject</td>
                        <td>Action</td>
                    </thead>
                    <tbody>
                        {% for p in pages %}
                        <tr>
                            <td>{{ p.updated }}</td>
                            <td>{% if p.position %}{{ p.position.route|truncatechars:20 }}{% else %}----------{% endif %}</td>
                            <td><a href="{% url 'dashboard:preview_page' p.id %}" target="_blank">{{ p.subject|truncatechars:65 }}</a></td>
                            <td>
                                <a class="label label-success" href="{% url 'dashboard:update_page' p.id %}">Edit</a>
                                <a class="label label-primary" href="{% url 'dashboard:preview_page' p.id %}" target="_blank">Preview</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/snippets.html
{% extends "dashboard/base.html" %}

{% block main %}
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h3 class="ghj">Snippets</h3>
                <h2><a class="label label-primary" href="{% url 'dashboard:new_snippet' %}">New</a></h2>
                <br>
                <table class="table table-bordered">
                    <thead>
                        <td>Pub_date</td>
                        <td>Subject</td>
                        <td>Position</td>
                        <td>Content</td>
                        <td>Action</td>
                    </thead>
                    <tbody>
                        {% for s in snippets %}
                        <tr>
                            <td>{{ s.updated }}</td>
                            <td>{{ s.subject|truncatechars:20 }}</td>
                            <td>{% if s.position %}{{ s.position.slug }}{% else %}----------{% endif %}</td>
                            <td>{{ s.content|truncatechars:45 }}</td>
                            <td>
                                <a class="label label-success" href="{% url 'dashboard:update_snippet' s.id %}">Edit</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/style.html
{% extends "dashboard/base.html" %}

{% block main %}
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1>Simple Sidebar</h1>
                <p>This template has a responsive menu toggling system. The menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will appear/disappear. On small screens, the page content will be pushed off canvas.</p>
                <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>.</p>
                <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block foot_js %}
{{ block.super }}
<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>
{% endblock %}